const Chess = require('@local/index');

test('Test simple 3 action checkmate', () => {
  var chess = new Chess();
  chess.move('1w. 1:e2:e3');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('1b. 1:f7:f6');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('2w. 2:Qd1:e2');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('2b. 2:Nb8:c6');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('3w. 3:Qe2:h5');
  chess.submit();
  expect(chess.inCheck).toBe(true);
  expect(chess.inCheckmate).toBe(true);
});

test('Test simple 3 action check but not checkmate', () => {
  var chess = new Chess();
  chess.move('1w. 1:a2:a3');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('1b. 1:a7:a6');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('2w. 2:e2:e3');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('2b. 2:f7:f5');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('3w. 3:Qd1:e2');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('3b. 3:Ng8:f6');
  chess.submit();
  expect(chess.inCheck).toBe(false);
  expect(chess.inCheckmate).toBe(false);
  chess.move('4w. 4:Qe2:h5');
  chess.submit();
  expect(chess.inCheck).toBe(true);
  expect(chess.inCheckmate).toBe(false);
});
